title = "王子豪的博客 "
baseURL = "https://zihaowang.online"
languageCode = "zh-cn"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "zh"
SectionPagesMenu = "main"
Paginate = 5                  # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "机器学习/ACGN/杂谈"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"

[caches]
  [caches.images]
    dir = ':cacheDir/images'