title = "王子豪的博客 "
baseURL = "https://zihaowang.online"
languageCode = "zh-cn"
theme = 'ananke'
resourceDir = "../resources"

DefaultContentLanguage = "zh"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true

[pagination]
  pagerSize = 5

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "机器学习/ACGN/杂谈"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 3

[[params.ananke_socials]]
name = "知乎"
url = "https://www.zhihu.com/people/wang-zi-hao-13-68"


[caches]
  [caches.assets]
    dir = ':resourceDir/_gen'
    maxAge = -1
  [caches.getcsv]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getjson]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getresource]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.images]
    dir = ':cacheDir/images'
    maxAge = -1
  [caches.misc]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.modules]
    dir = ':cacheDir/modules'
    maxAge = -1



